### PR TITLE
modified as sold model and 3D printable

### PR DESCRIPTION
**Pull request by manic-3dprint**

### CODE REVIEW

**Comment by borntoleave** [comment]
Could you note the changes you made to the original file? Like the change on certain dimensions. 
And where did you buy the servo? There are so many "fake" TowerPro servos.

**Comment by manic-3dprint** [comment]
it is your one we modified to be manifold , a sold model more suitable for
3d print and import for other cad software

**Comment by borntoleave** [comment]
I'm not sure about the overall compatibility. The original STL model was created with Fusion360. 
I tried to import the two versions into Cura, both look fine:
screen shot 2018-12-17 at 11 33 12 am

I also tried to open the new one with Solidworks2018 today, and here's the error message:
capture.
Although it could be displayed correctly afterwards, the original file doesn't have the error message. 

I noticed that you removed the 3 pin cable residue. Maybe it's introducing some gaps?

**Comment by manic-3dprint** [comment]
right, didnt put the wire part,   can put it back

**Comment by manic-3dprint** [comment]
and cura it is very good it can fix non manifold object for gcode , but if
import to the mesh software  meshmixer  you see your one is not a sold model

**Comment by borntoleave** [comment]
Please add back the wire. It's helpful for better wire arrangement when designing accessories. I'll merge after that revision. Thanks!

**Comment by borntoleave** [comment]
Done, although I noticed that there're long triangle signs on both sides if displayed on GitHub.
https://github.com/PetoiCamp/OpenCat/blob/master/Resources/STL/mg90d.stl

BTW, here's my fusion model for MG92B: http://bit.ly/2zxWjth

**Pull request merged**
